version: "3.7"

services:
  app:
    image: node:16-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 8078:8078
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mariadb:
    image: mariadb:10.6
    volumes:
      - todo-mysql-data:/var/lib/docker/volumes/todo-db/_data
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data: